services:
  app:
    container_name: restify
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8000:8000" 
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=restify_db
    depends_on:
      - db
    command: go run cmd/main.go
    networks:
      - javifood-network
  db:
    image: postgres:15
    container_name: restify_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: restify_db
    ports:
      - "5435:5432" 
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:

networks:
  javifood-network:
    external: true
