---
services:
  restify:
    container_name: restify
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    tty: true
    stdin_open: true
    volumes:
      - ./:/app
    depends_on:
      - db
    networks:
      - javifood-network
  db:
    image: postgres:15
    container_name: restify_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: restify_db
    ports:
      - "5435:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - javifood-network

volumes:
  pg_data:

networks:
  javifood-network:
    external: true
