basePath: /
host: localhost:3000
info:
  contact:
    email: contact@yuribarsotti.tech
    name: Yuri Barsotti
  description: Restify API docs
  title: JaviFood Restify
  version: "1.0"
paths:
  /api/v1/restaurants:
    post:
      consumes:
      - application/json
      responses:
        "201":
          description: Created
      summary: Create a restaurant
      tags:
      - restaurant
  /api/v1/restaurants/:
    post:
      consumes:
      - application/json
      responses:
        "201":
          description: Created
      summary: Create a restaurant
      tags:
      - restaurants
swagger: "2.0"
