// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Yuri Barsotti",
            "email": "contact@yuribarsotti.tech"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/restaurants/": {
            "post": {
                "description": "Allows to create a restaurant to the user",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "restaurants"
                ],
                "summary": "Create a restaurant",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID from Clerk JWT",
                        "name": "x-user",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Restaurant data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.payloadDto"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created"
                    }
                }
            }
        }
    },
    "definitions": {
        "handler.payloadDto": {
            "type": "object",
            "required": [
                "address",
                "close_time",
                "coordinate_x",
                "coordinate_y",
                "name",
                "open_time",
                "work_days"
            ],
            "properties": {
                "address": {
                    "type": "string",
                    "example": "3598 Pringle Drive"
                },
                "close_time": {
                    "type": "string",
                    "example": "22:30"
                },
                "coordinate_x": {
                    "type": "number",
                    "example": -21.74568
                },
                "coordinate_y": {
                    "type": "number",
                    "example": -89.34886
                },
                "name": {
                    "type": "string",
                    "example": "Restaurant XYZ"
                },
                "open_time": {
                    "type": "string",
                    "example": "10:00"
                },
                "user_id": {
                    "type": "string",
                    "example": "01953aa5-7d18-7781-bf1c-f425606b565f"
                },
                "work_days": {
                    "type": "array",
                    "items": {
                        "type": "string",
                        "enum": [
                            "Monday",
                            "Tuesday",
                            "Wednesday",
                            "Thursday",
                            "Friday",
                            "Saturday",
                            "Sunday"
                        ]
                    },
                    "example": [
                        "['Monday'",
                        " 'Tuesday']"
                    ]
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:3000",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "JaviFood Restify",
	Description:      "Restify API docs",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
